### ISSUE TITLE
Same/Difference

### ISSUE THREAD

**Issue by Hilal-Urun** [KengoWada/recommendation_system#5]
Hi @KengoWada , thanks for all information first, it was very helpful and I just did not catch the idea behind the same different count, could you give more informatio about that ?
Thanks for your time

**Comment by KengoWada** [comment]
Hey, I haven't looked at this in a while, do you mind pointing to the function that contains the issue.

**Comment by Hilal-Urun** [comment]
Thanks for your reply, of course ; https://github.com/KengoWada/recommendation_system/blob/97ca5554a39a0b3ca81dcd3676ae3188f8333f39/rj.py#L27 
in here

**Comment by KengoWada** [comment]
That is to check if the two different algorithms produce the same results. This is to demonstrate that the algorithm used matters given that there are more different outputs than the same outputs.

**Comment by Hilal-Urun** [comment]
okey I got it, thanks a lot
