### ISSUE TITLE
This code works with Python <= 3.5

### ISSUE THREAD

**Issue by lecchereng** [KengoWada/recommendation_system#8]
In requirements.txt it is required networkx==2.3 that imports gcd supposed to be inside fractions module. After python 3.5 gcd function was moved into math one.
If you use python > 3.5 you need to use network>=2.5 that updated the code.

Let me leave you a reference about the issue I found running your code on Python 3.9
[https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions](url)

Thank you

**Comment by KengoWada** [comment]
Fixed, now works with python >= 3.10.
